version: "3.8"
services:

  example-postgres:
    image: postgres:15.2
    container_name: example-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
